### ISSUE TITLE
Add Support for Window Functions: Lag/Lead

### ISSUE THREAD

**Issue by Deus3526** [zompinc/efcore-extensions#16]
As indicated in the title, I am requesting support for the window functions Lag and Lead.

I am working on a side project related to stock trading. In this project, I need to perform condition-based filtering. For example, I might want to filter cases where today's lowest stock price is greater than the highest price of the previous trading day. To implement such queries in C#, I require the support of Lag/Lead/STDEVP functions. Without these functions, I believe I would be limited to using raw SQL commands, which is not ideal for my workflow.

Thank you to the development team for your efforts and contributions to the EF window functions package. I've noticed a lack of extensions in this area, making your work incredibly important for developers like myself. Such a package offers greater flexibility and efficiency, which is particularly crucial in my projects. Once again, thank you for your hard work and innovation.

**Comment by virzak** [comment]
@Deus3526,

Thanks for the kind words. These functions will be implemented in the near future!

**Comment by virzak** [comment]
Lag and Lead are implemented in a separate branch and ready to be merged.

Can you try it out and see if the API is user friendly and self-explanatory?
I'm specifically interested in feedback respect / ignore nulls.

Nuget package to link to is [here](https://www.myget.org/feed/zomp-efcore-extensions/package/nuget/Zomp.EFCore.WindowFunctions.SqlServer).

**Comment by Deus3526** [comment]
I've installed the package and tested the Lag and Lead features. It seems to work well and meets my needs. The Lag/Lead API can be used in the same way as other window functions. Thanks!"

**Comment by virzak** [comment]
Version 8.0.10 has Lead and Lag. Will look into STDEVP separately soon.
