### ISSUE TITLE
I don't know if it's possible to protect against stupidity, but...

### ISSUE THREAD

**Issue by redwyre** [zompinc/efcore-extensions#19]
I managed to spend an hour or so with a colleague trying to figure out why our queries were suddenly running client side when adding the `RowNumber` function, but the issues was just that we didn't call `UseWindowFunctions` to enable the SQL generation.

If you can add something to check or add to the error message that it might not be configured, that would protect against this 😅

**Comment by virzak** [comment]
@redwyre, thanks for pointing that out after you got over the hurdle.

The message was basically a standard EF Core message. It is now appended with `One possible cause of this error is that '.UseWindowFunctions()' was not called on the 'DbContextOptionsBuilder' in 'OnConfiguring'.`

https://dotnetfiddle.net/RLK21Q

Do you think this would make it clearer for a future user?

This is available in the latest beta [8.0.19-beta](https://www.nuget.org/packages/Zomp.EFCore.WindowFunctions/8.0.19-beta)

**Comment by redwyre** [comment]
Perfect, thank you 😄
