### ISSUE TITLE
Empty over clause does not work

### ISSUE THREAD

**Issue by virzak** [zompinc/efcore-extensions#8]
Thanks for the [PR](https://github.com/zompinc/efcore-extensions/pull/7) @denis-tsv.

The reason why it wasn't implemented in the first place was because SQL Server needs at least one argument for this to work.
Will look into how this can be processed with PostgreSQL,

**Comment by denis-tsv** [comment]
It the lates version of SQL Server partition by and order by are optional for over 
https://learn.microsoft.com/en-us/sql/t-sql/queries/select-over-clause-transact-sql?view=sql-server-ver16

**Comment by denis-tsv** [comment]
In postgres over without parameters also OK
https://www.postgresql.org/docs/current/tutorial-window.html
